services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - shared-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
